name: pdb
services:
  test:
    image: pdb/test:${NODE_ENV:-development}
    build:
      context: .
      target: ${NODE_ENV:-development}
      args:
        APPLICATION_PORT: ${APPLICATION_PORT:-3000}
    container_name: test
    volumes:
      - type: volume
        source: pdb_test
        target: /srv/www/pdb_test
    security_opt:
      - no-new-privileges:true

volumes:
  pdb_test:
    name: pdb_test

networks:
  pdb_network:
    external: true