name: pdb
services:
  test:
    image: pdb/test:${NODE_ENV:-development}
    build:
      context: .
      target: ${NODE_ENV:-development}
      args:
        APPLICATION_PORT: ${APPLICATION_PORT:-3000}
    command: >
      sh -c "
        cp -n .env.example .env;
        ([ ! -d node_modules ] || [ ! $(ls -A node_modules) ]) && npm ci;
        npm run dev
      "
    container_name: test
    volumes:
      - type: bind
        source: $PWD
        target: /srv/www/pdb_test
    security_opt:
      - no-new-privileges:true

networks:
  pdb_network:
    external: true